/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import game.TTTWebService;
import game.TTTWebService_Service;
import java.awt.Color;


/**
 *
 * @author Vineeth
 */
public class MyScoreCard extends javax.swing.JFrame {

    /**
     * Creates new form MyScoreCard
     */
    private String username;
    
    public MyScoreCard() {
        initComponents();
    }
    // Creating constructor and passing the username as the parameter to dispaly it

    public MyScoreCard(String name) {
        username = name;
        initComponents();
        Showmystats();
        

    }
    /*
     Showstats fucntion will display the wins, loss and draws of the logged in user.
    */

    public void Showmystats() {
        int win=0;
        int loss=0;
        int draws=0;

        TTTWebService_Service webservice = new TTTWebService_Service();
        TTTWebService proxy = webservice.getTTTWebServicePort();
        String Stats = proxy.leagueTable();
        // Swich cases to handle the different errors 
         switch(Stats){
            case "ERROR-NOGAMES":
                ErrorMsg.setText("No Games");
                ErrorMsg.setForeground(Color.red);
                break;
            
            case "ERROR-DB ":
                ErrorMsg.setText("Failed to connect Database");
                ErrorMsg.setForeground(Color.red);
                break;
                // Default case will get the values and check the wins, loss, draws and pass the values
                //to the integer variables wins, loss, and draw
            default:
                String[] parts = Stats.split("\\n");
                String[][] Statics = new String[parts.length][5];
                for (int j = 0; j < parts.length; j++) {
                    String gameID= Statics[j][0] = parts[j].split(",")[0];
                    String p1 =Statics [j][1] = parts[j].split(",")[1];
                    String p2=Statics[j][2] = parts[j].split(",")[2];
                    String gameState = Statics[j][3] = parts[j].split(",")[3];
                    String timeStamp = Statics[j][4] = parts[j].split(",")[4];
                    if(username.equals(p1) || username.equals(p2)){
                        if(username.equals(p1) && gameState.equals("1")){
                            win++;
                        }else if(username.equals(p2)&& gameState.equals("2")){
                            win++;
                        }else if(gameState.equals("3")){
                            draws++;
                            }else if (!gameState.equals("0")&&!gameState.equals("-1") ){
                                loss++;
                            }
                
                
                    }
                }
              

        // Displaying the values of wins, loss and draws in the screen of the logged in useer
        wins.setText(Integer.toString(win)); 
        Loss.setText(Integer.toString(loss));
        Draw.setText(Integer.toString(draws));
        

    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wins = new javax.swing.JLabel();
        Loss = new javax.swing.JLabel();
        Draw = new javax.swing.JLabel();
        ErrorMsg = new javax.swing.JLabel();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("My Score Card");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Wins");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Loss");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Draw");

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Loss)
                                    .addComponent(Draw)
                                    .addComponent(wins)))
                            .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(OK)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(wins))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Loss))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Draw)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ErrorMsg)
                .addGap(18, 18, 18)
                .addComponent(OK)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyScoreCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyScoreCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyScoreCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyScoreCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyScoreCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Draw;
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JLabel Loss;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel wins;
    // End of variables declaration//GEN-END:variables
}
